<?php
// reportes.php
session_start();
// Incluye el header y sidebar
include 'docheader.php';  
include 'sidebar.php';
?>

<style>
/* Contenedor principal */
.content {
  padding-top: 80px;
  margin-left: 220px;
  transition: margin-left 0.3s ease;
}

/* Contenedor de la sección de reportes */
.reports-container {
  background-color: #fff;
  padding: 30px;
  margin: 20px auto;
  border-radius: 8px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  max-width: 1200px;
}

/* Encabezado de la sección */
.reports-header {
  margin-bottom: 20px;
  font-size: 1.5rem;
}

.reports-header h2 {
  color: #2c3e50;
}

.reports-header p {
  color: #666;
}

/* Filtros de búsqueda y botones */
.reports-filters {
  margin-bottom: 20px;
  display: flex;
  flex-wrap: wrap;
  align-items: center;
}

.reports-filters input,
.reports-filters select {
  padding: 10px;
  width: 300px;
  border: 1px solid #ddd;
  border-radius: 4px;
  margin-right: 10px;
}

.reports-filters button {
  padding: 10px 20px;
  border: none;
  border-radius: 4px;
  color: #fff;
  cursor: pointer;
}

.reports-filters button:first-of-type {
  background-color: #20a967;
}

.reports-filters button:last-of-type {
  background-color: #3498db;
  margin-left: auto;
}

/* Tabla de reportes */
table {
  width: 100%;
  border-collapse: collapse;
}

thead tr {
  background-color: #20a967;
  color: #fff;
}

th, td {
  padding: 12px 8px;
  text-align: left;
  font-size: 1.5rem;
}

tbody tr {
  border-bottom: 1px solid #ddd;
}

/* Enlaces de acción */
.action-links a {
  text-decoration: none;
  margin-right: 10px;
}

.action-links .view {
  color: #20a967;
}

.action-links .download {
  color: #3498db;
}

.action-links .delete {
  color: #e74c3c;
}
</style>

<!-- Contenedor principal -->
<div class="content" id="content">
  <!-- Contenedor de la sección de reportes -->
  <div class="reports-container">
    <!-- Encabezado de la sección -->
    <div class="reports-header">
      <h2>Reports</h2>
      <p>View and manage the reports generated by the platform.</p>
    </div>

    <!-- Filtros de búsqueda y botón de generar reporte -->
    <div class="reports-filters">
      <input type="text" placeholder="Search by title or description...">
      <select>
        <option value="">All statuses</option>
        <option value="pending">Pending</option>
        <option value="processed">Processed</option>
        <option value="resolved">Resolved</option>
      </select>
      <button>Search</button>
      <button>Generate Report</button>
    </div>

    <!-- Tabla de reportes -->
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Title</th>
          <th>Description</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <!-- Reporte 1 -->
        <tr>
          <td>2025-04-10</td>
          <td>Appointment Report</td>
          <td>List of confirmed and pending appointments.</td>
          <td>Processed</td>
          <td class="action-links">
            <a href="#" class="view">View</a>
            <a href="#" class="download">Download</a>
            <a href="#" class="delete">Delete</a>
          </td>
        </tr>
        <!-- Reporte 2 -->
        <tr>
          <td>2025-04-11</td>
          <td>Patient Report</td>
          <td>Summary of new patients and follow-ups.</td>
          <td>Pending</td>
          <td class="action-links">
            <a href="#" class="view">View</a>
            <a href="#" class="download">Download</a>
            <a href="#" class="delete">Delete</a>
          </td>
        </tr>
        <!-- Reporte 3 -->
        <tr>
          <td>2025-04-12</td>
          <td>Prescription Report</td>
          <td>Report of prescriptions generated by specialty.</td>
          <td>Resolved</td>
          <td class="action-links">
            <a href="#" class="view">View</a>
            <a href="#" class="download">Download</a>
            <a href="#" class="delete">Delete</a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <!-- Incluir el footer -->
  <?php include 'footer.php'; ?>
</div>
