<?php
// reportes.php
session_start();
// Include header and sidebar
include 'docheader.php';  // Contains the <head> section and the header of the page
include 'sidebar.php';    // Contains the sidebar navigation
?>
<!-- Main content container -->
<div class="content" id="content" style="
  /* Top padding to prevent content from being hidden behind the fixed header */
  padding-top: 80px;
  /* Left margin adjusted according to the expanded sidebar width (220px) */
  margin-left: 220px;
  transition: margin-left 0.3s ease;
">
  <!-- Main container for the Reports section -->
  <div class="reports-container" style="
    background-color: #fff; /* White background to highlight the content */
    padding: 30px;          /* Internal spacing */
    margin: 20px auto;      /* Vertical margin and horizontal centering */
    border-radius: 8px;     /* Rounded corners */
    box-shadow: 0 4px 12px rgba(0,0,0,0.1); /* Subtle shadow for depth */
    max-width: 1200px;      /* Maximum width for large screens */
  ">
    <!-- Section header -->
    <div class="reports-header" style="margin-bottom: 20px;">
      <h2 style="color: #2c3e50;">Reports</h2>
      <p style="color: #666;">View and manage the reports generated by the platform.</p>
    </div>

    <!-- Filters and search -->
    <div class="reports-filters" style="
      margin-bottom: 20px;
      display: flex;
      flex-wrap: wrap;
      align-items: center;
    ">
      <!-- Search input to filter reports by title or description -->
      <input type="text" placeholder="Search by title or description..." style="
        padding: 10px;                /* Internal spacing */
        width: 300px;                 /* Fixed width */
        border: 1px solid #ddd;       /* Subtle border */
        border-radius: 4px;           /* Rounded corners */
        margin-right: 10px;           /* Right margin for separation */
      ">
      <!-- Dropdown to filter reports by status -->
      <select style="
        padding: 10px;                /* Internal spacing */
        border: 1px solid #ddd;       /* Subtle border */
        border-radius: 4px;           /* Rounded corners */
        margin-right: 10px;           /* Right margin */
      ">
        <option value="">All statuses</option>
        <option value="pending">Pending</option>
        <option value="processed">Processed</option>
        <option value="resolved">Resolved</option>
      </select>
      <!-- Search button -->
      <button style="
        padding: 10px 20px;           /* Vertical and horizontal padding */
        background-color: #20a967;    /* Green background color */
        border: none;                 /* No border */
        border-radius: 4px;           /* Rounded corners */
        color: #fff;                  /* White text */
        cursor: pointer;              /* Pointer cursor on hover */
        margin-right: 10px;           /* Right margin */
      ">Search</button>
      <!-- Button to generate a new report, aligned to the right -->
      <button style="
        padding: 10px 20px;           /* Internal spacing */
        background-color: #3498db;    /* Blue background color */
        border: none;                 /* No border */
        border-radius: 4px;           /* Rounded corners */
        color: #fff;                  /* White text */
        cursor: pointer;              /* Pointer cursor */
        margin-left: auto;            /* Pushes the button to the far right */
      ">Generate Report</button>
    </div>

    <!-- Reports table -->
    <table style="
      width: 100%;                  /* Table occupies the full width of the container */
      border-collapse: collapse;    /* Removes space between cells */
    ">
      <!-- Table header -->
      <thead>
        <tr style="background-color: #20a967; color: #fff;">
          <!-- Each <th> defines a column with padding for better readability -->
          <th style="padding: 12px 8px; text-align: left;">Date</th>
          <th style="padding: 12px 8px; text-align: left;">Title</th>
          <th style="padding: 12px 8px; text-align: left;">Description</th>
          <th style="padding: 12px 8px; text-align: left;">Status</th>
          <th style="padding: 12px 8px; text-align: left;">Actions</th>
        </tr>
      </thead>
      <!-- Table body with example report data -->
      <tbody>
        <!-- Example Row 1 -->
        <tr style="border-bottom: 1px solid #ddd;">
          <td style="padding: 12px 8px;">2025-04-10</td>
          <td style="padding: 12px 8px;">Appointment Report</td>
          <td style="padding: 12px 8px;">List of confirmed and pending appointments.</td>
          <td style="padding: 12px 8px;">Processed</td>
          <td style="padding: 12px 8px;">
            <!-- Action links: View, Download, Delete -->
            <a href="#" style="color: #20a967; text-decoration: none; margin-right: 10px;">View</a>
            <a href="#" style="color: #3498db; text-decoration: none; margin-right: 10px;">Download</a>
            <a href="#" style="color: #e74c3c; text-decoration: none;">Delete</a>
          </td>
        </tr>
        <!-- Example Row 2 -->
        <tr style="border-bottom: 1px solid #ddd;">
          <td style="padding: 12px 8px;">2025-04-11</td>
          <td style="padding: 12px 8px;">Patient Report</td>
          <td style="padding: 12px 8px;">Summary of new patients and follow-ups.</td>
          <td style="padding: 12px 8px;">Pending</td>
          <td style="padding: 12px 8px;">
            <a href="#" style="color: #20a967; text-decoration: none; margin-right: 10px;">View</a>
            <a href="#" style="color: #3498db; text-decoration: none; margin-right: 10px;">Download</a>
            <a href="#" style="color: #e74c3c; text-decoration: none;">Delete</a>
          </td>
        </tr>
        <!-- Example Row 3 -->
        <tr>
          <td style="padding: 12px 8px;">2025-04-12</td>
          <td style="padding: 12px 8px;">Prescription Report</td>
          <td style="padding: 12px 8px;">Report of prescriptions generated by specialty.</td>
          <td style="padding: 12px 8px;">Resolved</td>
          <td style="padding: 12px 8px;">
            <a href="#" style="color: #20a967; text-decoration: none; margin-right: 10px;">View</a>
            <a href="#" style="color: #3498db; text-decoration: none; margin-right: 10px;">Download</a>
            <a href="#" style="color: #e74c3c; text-decoration: none;">Delete</a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <!-- Include the footer to maintain consistent design -->
  <?php include 'footer.php'; ?>
</div>
